### ISSUE TITLE
update document

### ISSUE THREAD

**Issue by sardine-mehico** [Alt-er/obsidian-sync-share-web#1]
### thank you for writing this amazing plugin. It is Quality!
When publishing a document, it generates a URL. When same document is updated, and published, it changes the URL so if it is shared with people, we need to send them new URL. Is there anyway oyu can modify to keep the same URL when publishing the document?

Also, is there a way to see all published documents and unpublish/delete them?

**Comment by Alt-er** [comment]
<img width="248" alt="image" src="https://github.com/user-attachments/assets/abdde68c-cc95-4699-ba89-8949cfdc342f">
<img width="573" alt="image" src="https://github.com/user-attachments/assets/1ff62b90-e344-4365-a205-6f27e705e6bd">

These functions are available

**Comment by sardine-mehico** [comment]
Wow, no need to go to server and manage there, just do it from Obsidian. You are a genious. And thank you for prompt reply.

**Comment by Alt-er** [comment]
You're welcome! If you found this helpful, could you please give the project a star? Thanks!

[plugin repo](https://github.com/Alt-er/obsidian-sync-share)

**Comment by sardine-mehico** [comment]
Done. Agagin, Thank you for making this plugin.

**Comment by Alt-er** [comment]
Thank you so much for starring the project! Your support is greatly appreciated!
